version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export ENV="production"' >> $BASH_ENV # Redirect ENV into $BASH_ENV
       - run: 
          name: "Install package"
          command: npm install
       - run:
          name: "Build files"
          command: npm run gulp build 
       - run: 
          name: "FTP Deploy"
          command: node .circleci/deployModules.js
       - run: echo "WE'RE ONLINE"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master